name: deploy to lambda

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: build
          run: | 
            npm install
            npx @vercel/ncc build src/index.ts -o dist

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: gh-action
          source: dist/index.js